Gestionale/Models/Stato.cs
using System;

namespace Gestionale.Models
{
    public class Stato
    {
        public int Id { get; set; }
        public DateTime DataConsegna { get; set; }
        public string StatoSpedizione { get; set; }
        public DateTime DataAggiornamento { get; set; }
        public bool InConsegna { get; set; }


    }
}

Gestionale/Controllers/CorriereController.cs
using Gestionale.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace Gestionale.Controllers
{
    public class CorriereController : Controller
    {

        public ActionResult Index()
        {


            return View();

        }


        //Codice per verificare le spedizioni in attesa di consegna
        public JsonResult AttesaConsegna()
        {
            string conn = ConfigurationManager.ConnectionStrings["GestionaleDB"].ConnectionString;
            SqlConnection sqlConnection = new SqlConnection(conn);

            List<Spedizione> spedizioniNonInConsegna = new List<Spedizione>();

            try
            {
                sqlConnection.Open();
                SqlCommand cmd = new SqlCommand("SELECT s.* " +
                                                "FROM SPEDIZIONI s " +
                                                "INNER JOIN STATO st ON s.IdSpedizione = st.IdSpedizione " +
                                                "WHERE st.DataAggiornamento = (SELECT MAX(DataAggiornamento) FROM STATO WHERE IdSpedizione = s.IdSpedizione) " +
                                                "AND st.InConsegna = 0 " +
                                                "AND s.IdSpedizione NOT IN (SELECT IdSpedizione FROM STATO WHERE InConsegna = 1)", sqlConnection);

                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    int Id = Convert.ToInt32(reader["IdSpedizione"]);
                    DateTime datasp = Convert.ToDateTime(reader["DataSpedizione"].ToString());
                    int peso = Convert.ToInt32(reader["Peso"].ToString());
                    string destinazione = reader["Destinazione"].ToString();
                    string indirizzo = reader["Indirizzo"].ToString();
                    string nome = reader["Nome"].ToString();
                    decimal costo = Convert.ToDecimal(reader["Costo"].ToString());

                    Spedizione spedizione = new Spedizione
                    {
                        id = Id,
                        DataSpedizione = datasp,
                        Peso = peso,
                        Destinazione = destinazione,
                        indirizzo = indirizzo,
                        Nome = nome,
                        Costo = costo
                    };

                    spedizioniNonInConsegna.Add(spedizione);
                }

                // Return the list as JSON
                return Json(spedizioniNonInConsegna, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Response.Write(ex.ToString());
                return Json(new { error = "An error occurred while fetching data." }, JsonRequestBehavior.AllowGet);
            }
            finally
            {
                sqlConnection.Close();
            }
        }

        //Codice per le consegne raggruppate per Città
        public JsonResult Citta()
        {
            string conn = ConfigurationManager.ConnectionStrings["GestionaleDB"].ConnectionString;
            SqlConnection sqlConnection = new SqlConnection(conn);

            List<Spedizione> cittaSpedizioni = new List<Spedizione>();

            try
            {
                sqlConnection.Open();
                SqlCommand cmd = new SqlCommand(
                    "SELECT Destinazione, COUNT(IdSpedizione) AS NumeroSpedizioni " +
                    "FROM SPEDIZIONI " +
                    "GROUP BY Destinazione",
                    sqlConnection);

                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    string destinazione = reader["Destinazione"].ToString();
                    int numeroSpedizioni = Convert.ToInt32(reader["NumeroSpedizioni"]);

                    Spedizione citta = new Spedizione
                    {
                        Destinazione = destinazione,
                        NumeroSpedizioni = numeroSpedizioni
                    };

                    cittaSpedizioni.Add(citta);
                }
            }
            catch (Exception ex)
            {
                Response.Write(ex.ToString());
            }
            finally
            {
                sqlConnection.Close();
            }


            return Json(cittaSpedizioni, JsonRequestBehavior.AllowGet);
        }


        //Codice per consegne in data odierna
        public JsonResult SpedizioniInConsegnaOggi()
        {
            string conn = ConfigurationManager.ConnectionStrings["GestionaleDB"].ConnectionString;
            SqlConnection sqlConnection = new SqlConnection(conn);

            List<Spedizione> spedizioniInConsegnaOggi = new List<Spedizione>();

            try
            {
                sqlConnection.Open();
                // Ottieni la data odierna
                DateTime dataOdierna = DateTime.Today;

                SqlCommand cmd = new SqlCommand(
                    "SELECT s.* " +
                    "FROM SPEDIZIONI s " +
                    "INNER JOIN STATO st ON s.IdSpedizione = st.IdSpedizione " +
                    "WHERE st.DataAggiornamento = @DataOdierna AND st.InConsegna = 1",
                    sqlConnection);

                // Imposta il parametro per la data odierna
                cmd.Parameters.AddWithValue("@DataOdierna", dataOdierna);

                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    int Id = Convert.ToInt32(reader["IdSpedizione"]);
                    DateTime datasp = Convert.ToDateTime(reader["DataSpedizione"].ToString());
                    int peso = Convert.ToInt32(reader["Peso"].ToString());
                    string destinazione = reader["Destinazione"].ToString();
                    string indirizzo = reader["Indirizzo"].ToString();
                    string nome = reader["Nome"].ToString();
                    decimal costo = Convert.ToDecimal(reader["Costo"].ToString());

                    Spedizione spedizione = new Spedizione
                    {
                        id = Id,
                        DataSpedizione = datasp,
                        Peso = peso,
                        Destinazione = destinazione,
                        indirizzo = indirizzo,
                        Nome = nome,
                        Costo = costo
                    };

                    spedizioniInConsegnaOggi.Add(spedizione);
                }

                // Restituisci la lista come JSON
                return Json(spedizioniInConsegnaOggi, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Response.Write(ex.ToString());
                return Json(new { error = "An error occurred while fetching data." }, JsonRequestBehavior.AllowGet);
            }
            finally
            {
                sqlConnection.Close();
            }
        }

    }
}

Gestionale/Views/Admin/Citta.cshtml
@{
    ViewBag.Title = "Citta";
}



<div class="container text-center mt-5">

    <h2 class="text-center">Lista di spedizioni raggruppate per Città destinataria</h2>

    <div class="table-responsive mt-4">
        <table class="table table-hover text-center w-50 mx-auto">

            <thead class="bg-warning">
                <tr>
                    <th>Destinazione</th>
                    <th>Numero Spedizioni</th>
                 
                </tr>
            </thead>
            <tbody class="bg-warning bg-opacity-25" id="tabellaSpedizioni">
            </tbody>
        </table>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $.ajax({
                url: '@Url.Action("Citta", "Corriere")',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    // Popola la tabella con i dati JSON
                    var tableBody = $('#tabellaSpedizioni');
                    $.each(data, function (index, item) {
                        var row = '<tr>';
                        row += '<td>' + item.Destinazione + '</td>';
                        row += '<td>' + item.NumeroSpedizioni + '</td>';
                        row += '</tr>';
                        tableBody.append(row);
                    });
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });
    </script>
}

Gestionale/Views/Admin/ConsegneInAttesa.cshtml
@{
    ViewBag.Title = "ConsegneInAttesa";
}



<div class="container text-center mt-5">

    <h2>Lista delle consegne in attesa </h2>

    <div class="table-responsive mt-4">
        <table class="table table-hover text-center w-75 mx-auto">

            <thead class="bg-warning">
                <tr>
                    <th>Destinazione</th>
                    <th>Indirizzo Spedizione</th>
                    <th>Peso</th>
                    <th>Costo</th>
                    <th>Nome</th>
                </tr>
            </thead>
            <tbody class="bg-warning bg-opacity-25" id="tabellaSpedizioni">
            </tbody>
        </table>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $.ajax({
                url: '@Url.Action("AttesaConsegna", "Corriere")',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    // Popola la tabella con i dati JSON
                    var tableBody = $('#tabellaSpedizioni');
                    $.each(data, function (index, item) {
                        var row = '<tr>';
                        row += '<td>' + item.Destinazione + '</td>';
                        row += '<td>' + item.indirizzo + '</td>';
                        row += '<td>' + item.Peso + "g" + '</td>';
                        row += '<td>' + item.Costo + "€" + '</td>';
                        row += '<td>' + item.Nome + '</td>';
                     

                        row += '</tr>';
                        tableBody.append(row);
                    });
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });
    </script>
}

Gestionale/Views/Admin/Elimina.cshtml
@model Gestionale.Models.Spedizione

@{
    ViewBag.Title = "Elimina Spedizione";
    
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-header">
                    <h2 class="card-title">Elimina Spedizione</h2>
                </div>
                <div class="card-body">
                    <p>Sei sicuro di voler eliminare questa spedizione?</p>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group text-center">
                            <input type="submit" value="Elimina" class="btn btn-danger" />
                            <a href="@Url.Action("Index", "Admin")" class="btn btn-warning">Annulla</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Gestionale/Views/Admin/InConsegnaOggi.cshtml
@{ 
    ViewBag.Title = "InConsegnaOggi";
}

<div class="container text-center mt-5">
   
    <h2 class="mt-3">Spedizioni in Consegna in data <span id="date"> </span></h2>

    <div class="table-responsive mt-4">
        <table class="table table-hover text-center w-75 mx-auto">
      
            <thead class="bg-warning">
                <tr>
                    <th>Destinazione</th>
                    <th>Indirizzo Spedizione</th>
                    <th>Peso</th>
                    <th>Costo</th>
                    <th>Nome</th>
                </tr>
            </thead>
            <tbody class="bg-warning bg-opacity-25" id="tabellaSpedizioni">
              
            </tbody>
        </table>
    </div>
</div>



@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            // Ottieni la data odierna
            let today = new Date();
            let day = today.getDate();
            let month = today.getMonth() + 1; // Mese è zero-based, quindi aggiungi 1
            let year = today.getFullYear();

            // Formatta la data 
            let formattedDate = day + '/' + month + '/' + year;

            // Imposta la data nel tuo elemento span
            $('#date').text(formattedDate);

            // Effettua la chiamata AJAX per recuperare le spedizioni
            $.ajax({
                url: '@Url.Action("SpedizioniInConsegnaOggi", "Corriere")',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    // Popola la tabella con i dati JSON
                    let tableBody = $('#tabellaSpedizioni');
                    $.each(data, function (index, item) {
                        let row = '<tr>';
                        row += '<td>' + item.Destinazione + '</td>';
                        row += '<td>' + item.indirizzo + '</td>';
                        row += '<td>' + item.Peso  + "g" + '</td>';
                        row += '<td>' + item.Costo + "€" + '</td>';
                        row += '<td>' + item.Nome + '</td>';
                        row += '</tr>';
                        tableBody.append(row);
                    });
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });
    </script>
}

Gestionale/Views/Admin/Index.cshtml
@model IEnumerable<Gestionale.Models.Spedizione>
@{
    ViewBag.Title = "Index";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="row">

        <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block shadow sidebar">
            <div class="position-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="#">
                            Admin Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="@Url.Action("Nuova", "Admin")">
                            Crea nuova Spedizione
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="@Url.Action("NewCliente", "Admin")">
                            Crea nuovo Cliente
                        </a>
                    </li>    
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="@Url.Action("ListaClienti", "Admin")">
                            Lista clienti
                        </a>
                    </li>    
                    
                   
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="@Url.Action("InConsegnaOggi", "Admin")">
                            Spedizioni in consegna 
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="@Url.Action("ConsegneInAttesa", "Admin")">
                            Verifica le spedizioni in attesa di consegna
                        </a>
                    </li>  
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="@Url.Action("Citta", "Admin")">
                            Verifica le spedizioni raggruppate per Città
                        </a>
                    </li>
                   
                   
                </ul>
            </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
         
            <h2>Lista di tutte le spedizioni</h2>

            <div class="table-responsive">
                <table class="table  table-hover  ">
                    <thead>
                        <tr>
                            <th>Destinazione</th>
                            <th>Indirizzo</th>
                            <th>Peso</th>
                            <th>Data Spedizione</th>
                            <th>Costo</th>
                            <th>Nome</th>
                            <th>Modifica</th>
                            <th>Gestione</th>
                            <th>Elimina</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Gestionale.Models.Spedizione s in Model)
                        {
                            <tr>
                                <td>@s.Destinazione</td>
                                <td>@s.indirizzo</td>
                                <td>@s.Peso</td>
                                <td>@s.DataSpedizione.ToString("dd/MM/yyyy")</td>
                                <td>@string.Format("{0:C}", s.Costo)</td>
                                <td>@s.Nome</td>
                                <td><a href="@Url.Action("Modifica", "Admin", new { idSpedizione = s.id })" class="btn btn-outline-warning">Modifica</a></td>
                                <td><a href="@Url.Action("Stato", "Admin", new { idSpedizione = s.id })" class="btn btn-outline-info">Stato</a></td>
                                <td><a href="@Url.Action("Elimina", "Admin")?id=@s.id" class="btn btn-danger">Elimina</a></td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </main>
    </div>
</div>

Gestionale/Views/Admin/ListaClienti.cshtml
@model IEnumerable<Gestionale.Models.Cliente>
@{
    ViewBag.Title = "ListaClienti";
}

<link href="~/Content/Site.css" rel="stylesheet" />
<div class="container-fluid w-50">

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

        <h2>Lista dei clienti</h2>

        <div class="table-responsive text-center">
            <table class="table  table-hover  ">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Codice fiscale o P.IVA</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (Gestionale.Models.Cliente cliente in Model)
                    {
                        <tr>

                            <td>@cliente.Nome</td>
                            <td>@cliente.CFoPIVA</td>
                           <td>
                           

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </main>
</div>
</div>

Gestionale/Views/Admin/Modifica.cshtml
@model Gestionale.Models.Spedizione

@{
    ViewBag.Title = "Modifica";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container ">
        <div class="row mx-auto">
            <div class="col-md-6 col-md-offset-3">
                <div class="card w-75">
                    <div class="card-body shadow">
                        <h4>Modifica Spedizione</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group">
                            <label class="form-label"> Ordine effettuato il: </label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DataSpedizione, new { htmlAttributes = new { @class = "form-control", Type = "date" } })
                                @Html.ValidationMessageFor(model => model.DataSpedizione, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="form-label"> Peso: </label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="form-label"> Città di arrivo: </label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Destinazione, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Destinazione, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="form-label"> Indirizzo di arrivo: </label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.indirizzo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.indirizzo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="form-label"> Indirizzato a: </label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="form-label"> Prezzo totale: </label>
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Costo, new { @class = "form-control", type = "text" })
                                @Html.ValidationMessageFor(model => model.Costo, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <a href="@Url.Action("Stato", "Admin", new { idSpedizione = Model.id })" class="btn btn-info mt-3 mb-3">Gestisci Stato Spedizione</a>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Salva" class="btn btn-outline-warning" />
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


}

Gestionale/Views/Admin/NewCliente.cshtml
@model Gestionale.Models.Cliente

@{
    ViewBag.Title = "NewCliente";
}



<div class="container ">
    <div class="row mx-auto">
        <div class="col-md-6 col-md-offset-3">
            <div class="card w-75">
                <div class="card-body shadow">
                    <h2 class="card-title">Nuovo Cliente</h2>
                    <hr />

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CFoPIVA, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.CFoPIVA, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CFoPIVA, "", new { @class = "text-danger" })
                        </div>



                        <div class="form-group">
                            <input type="submit" value="Crea" class="btn btn-primary mt-3" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Gestionale/Views/Admin/Nuova.cshtml
@model Gestionale.Models.Spedizione

@{
    ViewBag.Title = "Nuova";
}

<div class="container ">
    <div class="row mx-auto">
        <div class="col-md-6 col-md-offset-3">
            <div class="card w-75">
                <div class="card-body shadow">
                    <h2 class="card-title">Nuova Spedizione</h2> 
                    <hr />

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                <div class="form-group">
                    <label class="form-label"> Ordine effettuato il: </label>
                    @Html.EditorFor(model => model.DataSpedizione, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.DataSpedizione, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label class="form-label"> Peso: </label>
                    @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
                </div>

                        <div class="form-group">
                            <label class="form-label"> Città di arrivo: </label>
                            @Html.EditorFor(model => model.Destinazione, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Destinazione, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="form-label"> Indirizzo di arrivo: </label>
                            @Html.EditorFor(model => model.indirizzo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.indirizzo, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="form-label"> Indirizzato a: </label>
                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="form-label"> Prezzo totale: </label>
                            @Html.EditorFor(model => model.Costo, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                            @Html.ValidationMessageFor(model => model.Costo, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label"> Inviato da: </label>
                            @Html.DropDownListFor(m => m.IdCliente,
                                                    new SelectList(ViewBag.Clienti, "Value", "Text"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IdCliente, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Crea" class="btn btn-outline-success mt-3" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Gestionale/Views/Admin/Stato.cshtml
@model Gestionale.Models.Stato
@{
    ViewBag.Title = "Stato";
}

<div class="container">
    <div class="row mx-auto">
        <div class="col-md-6 col-md-offset-3">
            <div class="card w-75">
                <div class="card-body shadow">
                    <h2 class="card-title">Stato Spedizione</h2>
                    <hr />
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="mb-3">
                            <label class="form-label"> Data di consegna stimata: </label>
                            @Html.EditorFor(model => model.DataConsegna, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                            @Html.ValidationMessageFor(model => model.DataConsegna, "", new { @class = "text-danger" })
                        </div>

                        <div class="mb-3">
                            <label class="form-label"> Stato della spedizione: </label>
                            @Html.EditorFor(model => model.StatoSpedizione, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StatoSpedizione, "", new { @class = "text-danger" })
                        </div>

                        <div class="mb-3">
                            <label class="form-label"> Data aggiornamento: </label>
                            @Html.EditorFor(model => model.DataAggiornamento, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                            @Html.ValidationMessageFor(model => model.DataAggiornamento, "", new { @class = "text-danger" })
                        </div>

                        <div class="mb-3">
                            <label class="form-label"> Spedizione in Consegna? </label>
                            @Html.CheckBoxFor(model => model.InConsegna, new { @class = "form-check-input" })
                        </div>

                        <button type="submit" class="btn btn-success">Aggiorna Stato</button>
                    }
                </div>
            </div>
        </div>


    </div>
</div>